//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iJobRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string ClientID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Date_Of_Birth { get; set; }
        public string Gender { get; set; }
        public string Street_Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public int Postal_Code { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
