//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iJobRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequest
    {
        public int Job_Request_ID { get; set; }
        public string ClientID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time_Start { get; set; }
        public System.TimeSpan Time_End { get; set; }
        public string Category { get; set; }
        public Nullable<int> Num_Of_Labourers { get; set; }
        public string Job_Specification { get; set; }
        public string Location { get; set; }
        public bool Transport_Status { get; set; }
        public decimal Cost { get; set; }
        public bool Assigned_Status { get; set; }
    }
}
