//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iJobRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placement
    {
        public int Placement_ID { get; set; }
        public int Job_Request_ID { get; set; }
        public string Agent_ID { get; set; }
        public string Driver_ID { get; set; }
        public System.DateTime Date { get; set; }
        public bool Completion_Status { get; set; }
        public string Labourer_ID { get; set; }
    }
}
